# _*_ coding:utf-8 _*_

EXCEL_FONT = "宋体"
EXCEL_ALIGN = "center"
ENCODING = "UTF-8"
PASS = "PASS"
FAIL = "FAIL"
# 测试结果所在列
RESULT_COL = "K"
RESULT_COL_NUM = 11
ERR_MSG_COL = "L"
ERR_MSG_COL_NUM = 12


# ########Excel中的API属性标题###########
CASE_ID = "ID"
API_METHOD = "METHOD"
API_URL = "URL"
API_PARAMS = "PARAMS"
API_HEADERS = "HEADERS"
API_BODY = "BODY"
API_TYPE = "CONTENT-TYPE"
EXPECTED = "EXPECTED"
RESULT_MSG = "RESULT_ERR_MSG"
DATA_TYPE = "data"
JSON_TYPE = "json"
